### ISSUE TITLE
why does S3IterableDataset don't do sharding when worker_num > 0 ?

### ISSUE THREAD

**Issue by yangahau** [awslabs/s3-connector-for-pytorch#282]
### Tell us more about this new feature.

if i want see different sub-part of dataset for each worker, how to do?

**Comment by yangahau** [comment]
it's already supported. I see.

**Comment by IsaevIlya** [comment]
You're correct. S3IterableDataset has supported parallel and distributed training since version 1.3.0. To utilize this feature, simply pass `enable_sharding=True` when creating the dataset. For more details, please refer to the S3IterableDataset section : https://github.com/awslabs/s3-connector-for-pytorch?tab=readme-ov-file#s3iterabledataset
