### ISSUE TITLE
I am using container based credentials, is this connector already compatible?

### ISSUE THREAD

**Issue by rvencu** [awslabs/s3-connector-for-pytorch#75]
### Tell us more about this new feature.

I am setting in env container variables where tools like awscli, boto3, cpp sdk can generate proper credentials. Could you let me know if this connector can work in this environment?

My starting variables are AWS_CONTAINER_CREDENTIALS_FULL_URI and AWS_CONTAINER_AUTHORIZATION_TOKEN

**Comment by dnanuti** [comment]
Thank you for raising this!
We do not manage credentials directly, but our documentation has details about the [credentials configuration](https://github.com/awslabs/s3-connector-for-pytorch/blob/main/README.md#configuration) covered in our testing. It is on our roadmap to extend the testing to multiple configurations, including container credentials.
We will follow up on this issue when we have any updates.

**Comment by jamesbornholt** [comment]
Yes, ECS container credentials (`AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` and friends) are supported. I tested it just now, using an ECS task running the [AWS Deep Learning Container](https://github.com/aws/deep-learning-containers/blob/master/available_images.md#ec2-framework-containers-tested-on-ec2-ecs-and-eks-only) image with a container command like this:
```
/bin/bash -c "pip install s3torchconnector && python -c 'from s3torchconnector import S3IterableDataset; i = S3IterableDataset.from_prefix("s3://s3torchconnector-demo/geonet/images/",region="us-east-1"); print(next(iter(i)).key)'"
```

Let us know if this isn't working for you!

(It works because, under the hood, the S3 Connector for PyTorch is using the same S3 client as [Mountpoint for Amazon S3](https://github.com/awslabs/mountpoint-s3), and so anything you see in its [credentials documentation](https://github.com/awslabs/mountpoint-s3/blob/main/doc/CONFIGURATION.md#aws-credentials) should work here too).
